name: shorouk_news
description: A Flutter news application for Shorouk News

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and State Management
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP and API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Images and Media
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  youtube_player_flutter: ^8.1.2
  
  # HTML rendering
  flutter_html: ^3.0.0-beta.2
  
  # Push notifications (disabled)
  # firebase_core: ^2.24.2
  # firebase_messaging: ^14.7.9
  # firebase_analytics: ^10.7.4
  
  # Social sharing
  share_plus: ^7.2.1
  
  # URL launcher
  url_launcher: ^6.2.2
  
  # Web view
  webview_flutter: ^4.4.2
  
  # Ads (disabled)
  # google_mobile_ads: ^4.0.0
  
  # Utilities
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  
  # Loading and refresh
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  
  # Icons and fonts
  flutter_svg: ^2.0.9
  flutter_local_notifications: ^18.0.1
  video_player: ^2.10.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700

dependency_overrides:
  flutter_inappwebview: ^6.0.0

